<a href="https://colab.research.google.com/github/lunu5/diveintocode-ml/blob/master/Matrix_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

#[Problem 1] Matrix product is calculated manually
$$
AB = 
\left[
\begin{array}{ccc}
  (-1)\times0+2\times0+3\times2 & (-1)\times2+2\times2+3\times9 & (-1)\times1+2\times(-8)+3\times(-1) \\
  4\times0+(-5)\times0+6\times2 & 4\times2+(-5)\times2+6\times9 & 4\times1+(-5)\times(-8)+6\times(-1) \\
  7\times0+8\times0+(-9)\times2 & -7\times0+8\times2+(-9)\times9 & 7\times1+8\times(-8)+(-9)\times(-1)
\end{array}
\right]
=\left[
\begin{array}{ccc}
  6 & 29 & -20 \\
  12 & 52 & 38 \\
  -18 & -51 & -48
\end{array}
\right]
$$


#[Problem 2] Calculation by NumPy function

##Using ```np.matmul()```

In [2]:
print("Result when using np.matmul():\n{}".format(np.matmul(a_ndarray, b_ndarray)))

Result when using np.matmul():
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


##Using ```np.dot()```

In [3]:
print("Result when using np.dot():\n{}".format(np.dot(a_ndarray, b_ndarray)))

Result when using np.dot():
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


##Using ```@``` operator

In [4]:
print("Result when using @ operator:\n{}".format(a_ndarray @ b_ndarray))

Result when using @ operator:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


##Hand calculation from scratch implementation using NumPy

In [5]:
prod = np.array([[a_ndarray[0][0]*b_ndarray[0][0] + a_ndarray[0][1]*b_ndarray[1][0] + a_ndarray[0][2]*b_ndarray[2][0], a_ndarray[0][0]*b_ndarray[0][1] + a_ndarray[0][1]*b_ndarray[1][1] + a_ndarray[0][2]*b_ndarray[2][1], a_ndarray[0][0]*b_ndarray[0][2] + a_ndarray[0][1]*b_ndarray[1][2] + a_ndarray[0][2]*b_ndarray[2][2]],
                 [a_ndarray[1][0]*b_ndarray[0][0] + a_ndarray[1][1]*b_ndarray[1][0] + a_ndarray[1][2]*b_ndarray[2][0], a_ndarray[1][0]*b_ndarray[0][1] + a_ndarray[1][1]*b_ndarray[1][1] + a_ndarray[1][2]*b_ndarray[2][1], a_ndarray[1][0]*b_ndarray[0][2] + a_ndarray[1][1]*b_ndarray[1][2] + a_ndarray[1][2]*b_ndarray[2][2]],
                 [a_ndarray[2][0]*b_ndarray[0][0] + a_ndarray[2][1]*b_ndarray[1][0] + a_ndarray[2][2]*b_ndarray[2][0], a_ndarray[2][0]*b_ndarray[0][1] + a_ndarray[2][1]*b_ndarray[1][1] + a_ndarray[2][2]*b_ndarray[2][1], a_ndarray[2][0]*b_ndarray[0][2] + a_ndarray[2][1]*b_ndarray[1][2] + a_ndarray[2][2]*b_ndarray[2][2]]])
print("Result when using hand calculation from scratch implementation using NumPy:\n{}".format(prod))

Result when using hand calculation from scratch implementation using NumPy:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


#[Problem 3] Implementation of calculation of a certain element

In [6]:
result = np.zeros((3, 3))
for i in range(len(a_ndarray)):
   for j in range(len(b_ndarray[0])):
       for k in range(len(b_ndarray)):
           result[i][j] += a_ndarray[i][k] * b_ndarray[k][j]
print("Result when using NumPy functions:\n{}".format(result))

Result when using NumPy functions:
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


#[Problem 4] Creating a function that performs matrix multiplication

In [7]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
def matrixes_product(a, b):
  size = len(a)
  result = np.zeros((size, size))
  for i in range(size):
    for j in range(size):
       for k in range(len(b)):
           result[i][j] += a[i][k] * b[k][j]
  return result
print("Product of d_ndarray and e_ndarray:\n{}".format(matrixes_product(d_ndarray, e_ndarray)))

Product of d_ndarray and e_ndarray:
[[ 21. -18.]
 [-66.  57.]]


#[Problem 5] Judge the input whose calculation is not defined

In [8]:
def matrixes_product_judge(a, b):
  size = len(a)
  if len(b[0]) != size:
    print("Error, incompatible shapes")
    return
  result = np.zeros((size, size))
  for i in range(size):
    for j in range(size):
       for k in range(len(b)):
           result[i][j] += a[i][k] * b[k][j]
  return result
print("Product of d_ndarray and e_ndarray:\n")
matrixes_product_judge(d_ndarray, e_ndarray)

Product of d_ndarray and e_ndarray:

Error, incompatible shapes


#[Problem 6] Transposition

In [9]:
print("Product of d_ndarray and e_ndarray:\n{}".format(matrixes_product_judge(d_ndarray, e_ndarray.T)))


Product of d_ndarray and e_ndarray:
[[ 46.  -4.]
 [-34.  73.]]
