<a href="https://colab.research.google.com/github/lunu5/diveintocode-ml/blob/master/Utilization_of_Object_Oriented.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("Mean :", scaler.mean_)
print("Variance :", scaler.var_)
X_std = scaler.transform(X)

Mean : [4.86 3.31 1.45 0.22]
Variance : [0.0764 0.0849 0.0105 0.0056]


##Instantiation

In [2]:
scaler = StandardScaler()
scaler0 = StandardScaler()
scaler1 = StandardScaler()
scaler2 = StandardScaler()

#[Problem 1] Enumeration of classes used so far

##Some class I have recently use


*   RandomForestClassifier from sklearn
*   DecisionTreeClassifier from sklearn
*   LinearRegression from sklearn
*   DataFrame from Pandas
*   Axes from matplotlib



##Method

In [3]:
scaler.fit(X)

StandardScaler(copy=True, with_mean=True, with_std=True)

##Instance variable (attribute)

In [4]:
print("平均 : {}".format(scaler.mean_)) # 平均 : [4.86 3.31 1.45 0.22]
print("分散 : {}".format(scaler.var_)) # 分散 : [0.0764 0.0849 0.0105 0.0056]

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]


#[Problem 2] Enumeration of methods and instance variables used so far

##Some method and instance variable were used in the previous assignments

###Method

*   `pandas.DataFrame.info` This method prints information about a DataFrame including the index dtype and columns, non-null values and memory usage.

*   `pandas.DataFrame.nlargest` This method return the first n rows with the largest values in columns, in descending order. The columns that are not specified are returned as well, but not used for ordering.

*   `pandas.DataFrame.isnull` This method return a boolean same-sized object indicating if the values are NA. NA values, such as None or numpy.NaN, gets mapped to True values. Everything else gets mapped to False values.

*   `pandas.DataFrame.drop` This method remove rows or columns by specifying label names and corresponding axis, or by specifying directly index or column names. When using a multi-index, labels on different levels can be removed by specifying the level.

*   `pandas.Series.corr` This method compute correlation with other Series, excluding missing values.


###Instance variable


*   `sklearn.datasets.load_irisload_iris().data`({ndarray, dataframe} of shape (150, 4)) The data matrix.

*   `sklearn.datasets.load_irisload_iris().target`({ndarray, Series} of shape (150,)) The classification target

*   `sklearn.datasets.load_irisload_iris().feature_names`(list) The names of the dataset columns.

*   `pandas.DataFrame.index`(Index) The index (row labels) of the DataFrame.

*   `pandas.DataFrame.columns`(Index) The column labels of the DataFrame.









In [5]:
l = ['a']
l.append('b') # listのappendメソッド

In [6]:
s = 'Hello, World!'
s.find('W') # strのfindメソッド

7

##Method uses instance variable

In [7]:
X_std = scaler.transform(X)

#[Problem 3] Creating a standardized class by scratch

In [8]:
class ScratchStandardScaler():
    """
    Class for standardization

    Attributes
    ----------
    mean_ : The following form ndarray, shape(n_features,)
        Mean
    var_ : The following form ndarray, shape(n_features,)
        Variance
    """
    def fit(self, X):
        """
        Calculate the mean and standard deviation for standardization

        Parameters
        ----------
        X : The following form ndarray, shape (n_samples, n_features)
            Training data
        """
        m = []
        v = []
        for i in range(X.shape[1]):
          m.append(X[:, i].mean())
          v.append(X[:, i].var())
        self.mean_ = m
        self.var_ = v

    def transform(self, X):
        """
        Standardize using the value obtained in fit()
        Parameters
        ----------
        X : The following form ndarray, shape (n_samples, n_features)
            Feature value

        Returns
        ----------
        X_scaled : The following form ndarray, shape (n_samples, n_features)
            Standardized special amount
        """
        X_scaled = (X - self.mean_)/self.var_
        return X_scaled

In [9]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.859999999999999, 3.31, 1.45, 0.22000000000000003]
分散 : [0.07640000000000002, 0.0849, 0.010499999999999999, 0.005599999999999999]
[[  3.14136126   2.23792697  -4.76190476  -3.57142857]
 [  0.52356021  -3.65135453  -4.76190476  -3.57142857]
 [ -2.09424084  -1.29564193 -14.28571429  -3.57142857]
 [ -3.40314136  -2.47349823   4.76190476  -3.57142857]
 [  1.83246073   3.41578327  -4.76190476  -3.57142857]
 [  7.06806283   6.94935218  23.80952381  32.14285714]
 [ -3.40314136   1.06007067  -4.76190476  14.28571429]
 [  1.83246073   1.06007067   4.76190476  -3.57142857]
 [ -6.02094241  -4.82921084  -4.76190476  -3.57142857]
 [  0.52356021  -2.47349823   4.76190476 -21.42857143]]


##Special methods

In [10]:
def __init__(self, copy=True, with_mean=True, with_std=True):
    self.with_mean = with_mean
    self.with_std = with_std
    self.copy = copy

In [11]:
class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8


#[Problem 4] Creating a class that performs 4 arithmetic operations

In [12]:
class ArithmeticOperations():
    """
    Performs 4 simple arithmetic operations

    Parameters
    ----------
    value : float or int
        Initial value
    Attributes
    ----------
    value : float or int
        Calculation result
    """

    def __init__(self, value):
        if type(value) != int and type(value) != float:
            self.value = 0
            raise Exception("Non-numeric input, initial value set to 0.")
        else: 
            self.value = value
            print("Initial value {} has been set".format(self.value))
        
    def add(self, value2):
        """
        Add the received argument to self.value
        """
        self.value += value2
        
    def subtract(self, value2):
        """
        Subtract the self.value by the received argument
        """
        self.value -= value2

    def multiply(self, value2):
        """
        Multiply the received argument to self.value
        """
        self.value *= value2

    def divide(self, value2):
        """
        Divide the received argument to self.value
        """
        self.value /= value2
result = ArithmeticOperations(6)
print("Value : {}".format(result.value))
result.add(3)
print("Value : {}".format(result.value))
result.subtract(1)
print("Value : {}".format(result.value))
result.multiply(4)
print("Value : {}".format(result.value))
result.divide(5)
print("Value : {}".format(result.value))

Initial value 6 has been set
Value : 6
Value : 9
Value : 8
Value : 32
Value : 6.4
